### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [nosthas/f1-3-c2p1-colmar-academy#5]
Grade: **Meets Expectations**

Overall, this project is working great! I really like how you downloaded all of the images and put them in a local resource folder as this is essential for faster page loading and proper project organization. On top of that you added alt tags to all of your images in order to give our users a text descriptor in the event the images are not loading. Typically we will give suggestions on what to change about the project, but this project is really well done! Next steps, I would try making some additional pages for the Colmar site, and make the links go to those pages. Try to maintain the same responsiveness and theme in these new pages.

Very nicely done!

**Comment by nosthas** [comment]
Thanks for your review Conner.
